from typing import Any, Mapping, Optional, Union

class Task:
    @property
    def id(self) -> str: ...
    def cancel(self) -> None: ...
    async def result(self) -> dict[str, Any]: ...

class SessionLease:
    agent_index: int
    async def ask(self, prompt: Union[str, Mapping[str, Any]]) -> dict[str, Any]: ...
    async def finish(self) -> None: ...
    async def __aenter__(self) -> SessionLease: ...
    async def __aexit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...

class AgentPool:
    def __init__(self, options: Mapping[str, Any]) -> None: ...
    def submit(self, prompt: Union[str, Mapping[str, Any]], agent_index: Optional[int] = ...) -> Task: ...
    async def acquire(self, agent_index: Optional[int] = ...) -> SessionLease: ...
    def submit_retrying(
        self,
        prompt: Union[str, Mapping[str, Any]],
        *,
        max_attempts: int,
        feedback_template: str,
        agent_index: Optional[int] = ...,
    ) -> Task: ...
    def status(self) -> dict[str, Any]: ...
    async def close(self, *, drain: bool = ...) -> dict[str, Any]: ...
    async def __aenter__(self) -> "AgentPool": ...
    async def __aexit__(self, exc_type: Any, exc: Any, traceback: Any) -> None: ...
