from typing import Optional

class NativeLeaseRequest:
    def cancel(self) -> None: ...
    def wait(self) -> NativeSessionLease: ...

class NativeSessionLease:
    @property
    def agent_index(self) -> int: ...
    def ask(self, prompt_json: str) -> str: ...
    def finish(self) -> None: ...

class NativeAgentPool:
    def __new__(cls, config_json: str) -> "NativeAgentPool": ...
    def request_lease(self, agent_index: Optional[int] = ...) -> NativeLeaseRequest: ...
    def status_json(self) -> str: ...
    def close(self, drain: bool = ...) -> str: ...
