from typing import Optional

class NativeTask:
    @property
    def id(self) -> str: ...
    def cancel(self) -> None: ...
    def result(self) -> str: ...

class NativeLeaseRequest:
    def cancel(self) -> None: ...
    def wait(self) -> NativeSessionLease: ...

class NativeSessionLease:
    @property
    def agent_index(self) -> int: ...
    def ask(self, prompt_json: str) -> str: ...
    def finish(self) -> None: ...

class NativeAgentPool:
    def __new__(cls, config_json: str) -> "NativeAgentPool": ...
    def submit(self, prompt_json: str, agent_index: Optional[int] = ...) -> NativeTask: ...
    def request_lease(self, agent_index: Optional[int] = ...) -> NativeLeaseRequest: ...
    def submit_retrying(
        self,
        prompt_json: str,
        max_attempts: int,
        feedback_template: str,
        agent_index: Optional[int] = ...,
    ) -> NativeTask: ...
    def status_json(self) -> str: ...
    def close(self, drain: bool = ...) -> str: ...
